### ISSUE TITLE
Error on tm.get_mailbox(email)

### ISSUE THREAD

**Issue by ghost** [saippuakauppias/temp-mail#6]
```
Traceback (most recent call last):
  File "/Users/myusername/Dropbox/Python/Projects/RCGspam/main.py", line 32, in <module>
    mailbox = tm.get_mailbox(email)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/tempmail.py", line 92, in get_mailbox
    email_hash = self.get_hash(email)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/tempmail.py", line 79, in get_hash
    return md5(email).hexdigest()
TypeError: Unicode-objects must be encoded before hashing
```

**Comment by mak1001** [comment]
Edit tempmail.py:
find get_hash function
change 
`return md5(email).hexdigest()
`
to
` return md5(email.encode('utf-8')).hexdigest()`
